from celery_worker import celery_app
from model import db, Doctor, Appointment
from datetime import date
from dateutil.relativedelta import relativedelta
import os

@celery_app.task(name='tasks.monthly_report.generate_reports')
def generate_reports():
    # Calculate the previous month span
    today = date.today()
    first_day_of_current_month = today.replace(day=1)
    last_month_start = first_day_of_current_month - relativedelta(months=1)
    last_month_end = first_day_of_current_month - relativedelta(days=1)
    
    month_name = last_month_start.strftime("%B_%Y")
    
    exports_dir = os.path.join(os.path.dirname(__file__), '..', 'static', 'reports')
    os.makedirs(exports_dir, exist_ok=True)
    
    active_doctors = Doctor.query.filter_by(is_blacklisted=False).all()
    count = 0
    
    for doc in active_doctors:
        # Get appointments for this doctor in the last month
        appointments = Appointment.query.filter(
            Appointment.doctor_id == doc.id,
            Appointment.date >= last_month_start,
            Appointment.date <= last_month_end
        ).all()
        
        completed = [a for a in appointments if a.status == 'Completed']
        cancelled = [a for a in appointments if a.status == 'Cancelled']
        no_shows = [a for a in appointments if a.status == 'Booked'] # Past booked are no shows
        
        # Build HTML
        html_content = f"""
        <html>
        <head>
            <title>Monthly performance Report - {doc.full_name}</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; color: #333; }}
                table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #14b8a6; color: white; }}
                h2, h3 {{ color: #0f766e; }}
            </style>
        </head>
        <body>
            <h2>ZenCura Monthly Report: {last_month_start.strftime('%B %Y')}</h2>
            <h3>Doctor: {doc.full_name} ({doc.department.name})</h3>
            <hr>
            <p><strong>Total Appointments Scheduled:</strong> {len(appointments)}</p>
            <p><strong>Completed Visits:</strong> {len(completed)}</p>
            <p><strong>Cancelled/No-shows:</strong> {len(cancelled) + len(no_shows)}</p>
            
            <h4>Details of Completed Visits</h4>
            <table>
                <thead>
                    <tr><th>Date</th><th>Patient</th><th>Diagnosis Info</th></tr>
                </thead>
                <tbody>
        """
        
        for apt in completed:
            diag = apt.treatment.diagnosis if apt.treatment else "None"
            html_content += f"<tr><td>{apt.date.isoformat()}</td><td>{apt.patient.full_name}</td><td>{diag}</td></tr>"
            
        html_content += """
                </tbody>
            </table>
            <p style="margin-top:40px; font-size:12px; color:#888;">Auto-generated by ZenCura Hospital Management System (Celery Job)</p>
        </body>
        </html>
        """
        
        filename = f"report_doc_{doc.id}_{month_name}.html"
        file_path = os.path.join(exports_dir, filename)
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
            
        count += 1
        
    return f"Successfully generated {count} doctor reports for {month_name}"
